[05/01/21]-[11:33:02] ERROR- Unable to load settings
[05/01/21]-[11:33:02] ERROR- java.io.FileNotFoundException: /home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/config/preferences.xml (No such file or directory)
[05/01/21]-[11:33:02] ERROR- 	at java.io.FileOutputStream.open0(Native Method)
[05/01/21]-[11:33:02] ERROR- 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[05/01/21]-[11:33:02] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[05/01/21]-[11:33:02] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[05/01/21]-[11:33:02] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:33:02] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:33:02] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:33:02] ERROR- inra.stics.exception.SticsException
[05/01/21]-[11:33:02] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:33:02] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:33:02] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:33:02] INFO - Modulostics files generation..
[05/01/21]-[11:33:02] INFO - Generating txt files ...
[05/01/21]-[11:33:02] INFO - An error occurs during the generation of the plant file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/corn/ficplt1.txt" from the file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/plant/corn_plt.xml".
[05/01/21]-[11:42:26] ERROR- Unable to load settings
[05/01/21]-[11:42:26] ERROR- java.io.FileNotFoundException: /home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/config/preferences.xml (No such file or directory)
[05/01/21]-[11:42:26] ERROR- 	at java.io.FileOutputStream.open0(Native Method)
[05/01/21]-[11:42:26] ERROR- 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[05/01/21]-[11:42:26] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[05/01/21]-[11:42:26] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[05/01/21]-[11:42:26] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:42:26] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:42:26] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:42:26] ERROR- inra.stics.exception.SticsException
[05/01/21]-[11:42:26] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:42:26] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:42:26] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:42:26] INFO - Modulostics files generation..
[05/01/21]-[11:42:26] INFO - Generating txt files ...
[05/01/21]-[11:42:26] INFO - An error occurs during the generation of the plant file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/corn/ficplt1.txt" from the file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/plant/corn_plt.xml".
[05/01/21]-[11:43:43] ERROR- Unable to load settings
[05/01/21]-[11:43:43] ERROR- java.io.FileNotFoundException: /home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/config/preferences.xml (No such file or directory)
[05/01/21]-[11:43:43] ERROR- 	at java.io.FileOutputStream.open0(Native Method)
[05/01/21]-[11:43:43] ERROR- 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[05/01/21]-[11:43:43] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[05/01/21]-[11:43:43] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[05/01/21]-[11:43:43] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:43:43] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:43:43] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:43:43] ERROR- inra.stics.exception.SticsException
[05/01/21]-[11:43:43] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:43:43] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:43:43] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:43:43] INFO - Modulostics files generation..
[05/01/21]-[11:43:43] INFO - Generating txt files ...
[05/01/21]-[11:43:43] INFO - An error occurs during the generation of the plant file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/corn/ficplt1.txt" from the file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/plant/corn_plt.xml".
[05/01/21]-[11:50:22] ERROR- Unable to load settings
[05/01/21]-[11:50:22] ERROR- java.io.FileNotFoundException: /home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/config/preferences.xml (No such file or directory)
[05/01/21]-[11:50:22] ERROR- 	at java.io.FileOutputStream.open0(Native Method)
[05/01/21]-[11:50:22] ERROR- 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[05/01/21]-[11:50:22] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[05/01/21]-[11:50:22] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[05/01/21]-[11:50:22] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:50:22] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:50:22] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:50:22] ERROR- inra.stics.exception.SticsException
[05/01/21]-[11:50:22] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:50:22] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:50:22] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:50:22] INFO - Modulostics files generation..
[05/01/21]-[11:50:22] INFO - Generating txt files ...
[05/01/21]-[11:50:22] INFO - An error occurs during the generation of the plant file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/corn/ficplt1.txt" from the file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/plant/corn_plt.xml".
[05/01/21]-[11:50:54] ERROR- Unable to load settings
[05/01/21]-[11:50:54] ERROR- java.io.FileNotFoundException: /home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/config/preferences.xml (No such file or directory)
[05/01/21]-[11:50:54] ERROR- 	at java.io.FileOutputStream.open0(Native Method)
[05/01/21]-[11:50:54] ERROR- 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[05/01/21]-[11:50:54] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[05/01/21]-[11:50:54] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[05/01/21]-[11:50:54] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:50:54] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:50:54] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:50:54] ERROR- inra.stics.exception.SticsException
[05/01/21]-[11:50:54] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:50:54] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:50:54] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:50:54] INFO - Modulostics files generation..
[05/01/21]-[11:50:54] INFO - Generating txt files ...
[05/01/21]-[11:50:54] INFO - An error occurs during the generation of the plant file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/corn/ficplt1.txt" from the file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/plant/corn_plt.xml".
[05/01/21]-[11:51:01] ERROR- Unable to load settings
[05/01/21]-[11:51:01] ERROR- java.io.FileNotFoundException: /home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/config/preferences.xml (No such file or directory)
[05/01/21]-[11:51:01] ERROR- 	at java.io.FileOutputStream.open0(Native Method)
[05/01/21]-[11:51:01] ERROR- 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[05/01/21]-[11:51:01] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[05/01/21]-[11:51:01] ERROR- 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[05/01/21]-[11:51:01] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:51:01] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:51:01] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:51:01] ERROR- inra.stics.exception.SticsException
[05/01/21]-[11:51:01] ERROR- 	at inra.stics.main.Settings.save(Unknown Source)
[05/01/21]-[11:51:01] ERROR- 	at inra.stics.main.Settings.setDirectory(Unknown Source)
[05/01/21]-[11:51:01] ERROR- 	at inra.stics.console.SticsBatch.main(Unknown Source)
[05/01/21]-[11:51:01] INFO - Modulostics files generation..
[05/01/21]-[11:51:01] INFO - Generating txt files ...
[05/01/21]-[11:51:01] INFO - An error occurs during the generation of the plant file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/corn/ficplt1.txt" from the file "/home/ahaddon/Dropbox/Work/ReUse/code/stics/pyScripts/plant/corn_plt.xml".
